### PR TITLE
Binaries as FastCGI parameters

### PR DESCRIPTION
**Pull request by evbogdanov**
Let's say I want to pass `{"NAME", <<"VALUE">>}` to the FastCGI server:
```
out(Arg) ->
	yaws_cgi:call_fcgi_responder(
		Arg,
		[
			{app_server_host, my_app:conf(fcgi_host)},
			{app_server_port, my_app:conf(fcgi_port)},
			{extra_env, [
				{"NAME", <<"VALUE">>}
			]}
		]
	).
```
My little patch handles it.

Interestingly, this also fixed unicode issue with non-ASCII urls. For example, when I tried to reach `127.0.0.1:1806/ёжик` server stopped responding. Now it works like a charm.

### CODE REVIEW

**Comment by vinoski** [comment]
Do all tests still pass, and are any new tests needed for this? Does any documentation need to change?

**Comment by evbogdanov** [comment]
Yes. Everything looks good.

As you can see, the changes are tiny and they don't affect existing API or documentation.

**Comment by vinoski** [comment]
The change is bigger than you think. Your example shows use of `extra_env`, which is mentioned in the `yaws_api.5` man page (and in fact is documented incorrectly there), and another part of the code in `yaws_cgi.erl` uses `extra_env` as well.

Also, the way you indented the revised `if` expressions doesn't match the rest of Yaws code. We use the emacs `erlang-mode` indentation style.

I've pulled your branch to my clone, have fixed the man page and the indentation, and will check to see if we already have tests that cover these changes.

**Comment by vinoski** [comment]
Your change works for FCGI because it all eventually gets sent over TCP, and `gen_tcp` doesn't care if you send lists or binaries. But looking more carefully at the code in `yaws_cgi.erl`, we see that in the [`cgi_worker/7` function](https://github.com/klacke/yaws/blob/master/src/yaws_cgi.erl#L536-L545) an `extra_env` is used to build an `env` for the [`erlang:open_port/2` function](http://www.erlang.org/doc/man/erlang.html#open_port-2). The documentation for that function specifies that that `env` is `[{Name :: string(), Val :: string() | false}]`; `Val` here is clearly not allowed to be a binary. Changing the Yaws documentation to allow a binary in `extra_env` values means this code has to be modified as well to change any such binaries to lists before passing them to `open_port/2`. I'll make this change in my clone.

**Comment by vinoski** [comment]
I pushed a modified commit to master. Thanks for contributing this.

**Comment by evbogdanov** [comment]
Thank you, @vinoski. You're a rockstar!

**Pull request closed without merging**
