### PR TITLE
Add yaws_websockets:close/2

### PR DESCRIPTION
**Pull request by surik**

### CODE REVIEW

**Comment by vinoski** [comment]
I think there should also be a `close/1` that defaults `Reason` to `normal`.

**Comment by vinoski** [comment]
Great, thanks. I'll merge this soon.

**Comment by vinoski** [comment]
Looking into this more, I'm wondering why returning `{close, CloseReason}` from a callback module's `handle_message/1` or `handle_message/2` isn't good enough? Under what conditions do you need an explicit `close/1,2` call? Also, what should a `handle_message` callback return if it's already called `close/1,2`?

**Comment by surik** [comment]
Yes, I could do this via ```handle_message```, but I think ```close/1,2``` method is good way for API. For example, I can write this ```yaws_websocket:close(Pid)``` from any part of system and don't need write code in callback module.
If ```close/1,2``` call, process will stopped after timeout. Maybe we should stop process immediately?

**Comment by vinoski** [comment]
Rather than having applications call `yaws_websocket:close/1,2` directly we need `yaws_api:websocket_close/1,2` to match the existing API. The documentation needs to be augmented for this new call. Surprisingly there are no tests for these calls, but there are example apps, so those likely need to be extended as well.

I've fetched your commits into a branch in my clone and will work on these additional items.

**Comment by vinoski** [comment]
I'll also note, though I haven't yet confirmed it, that there might be a chance for deadlock here. If a `close` function is invoked from a callback module call, it can lead to the need to invoke the callback's `terminate` function, and that might deadlock since the call is already executing within the callback. It depends on how the callback module is implemented; if it's a `gen_server`, a deadlock is definitely possible. I'll need to investigate further.

**Comment by vinoski** [comment]
Slightly modified, but now rebased to master. Thanks for your contribution.

**Pull request closed without merging**
