### PR TITLE
Fix trace log not catching the first request (refactoring)

### PR DESCRIPTION
**Pull request by andreineculau**
I see klacke already committed a fix for the issue in https://github.com/klacke/yaws/commit/ebfb12c8f395b0c9b3ad01fb3a3866ac735f7c0c

Without knowing his commit, I ended up with a little cleaning/deduplication instead.
Have a look, but maybe it's not worth it.

### CODE REVIEW

**Comment by vinoski** [comment]
Thanks, I'll take a look.

**Comment by vinoski** [comment]
Other than my previous comment, I think this looks good. I'm going to change the call to `hard_setconf/2` in `yaws_api` to pattern-match the return value, and then get this to master. Thanks again.

**Comment by andreineculau** [comment]
Ah, I went too far. Good eyes!
Thank **you**

cc @JohanVikman

**Comment by vinoski** [comment]
This is now on master.

**Pull request closed without merging**
