### PR TITLE
randome/random.

### PR DESCRIPTION
**Pull request by cmeiklejohn**

### CODE REVIEW

**Comment by capflam** [comment]
Thanks @cmeiklejohn. I will merge it very soon.

**Comment by vinoski** [comment]
@capflam can verify but I think the `randome` spelling is intentional, to avoid a compilation warning under 19.0 due to `warnings_as_errors` being enabled. Changing `randome` to `random` causes this error:

    compile: warnings being treated as errors
    yaws_dynopts.erl:136: random:seed/3: the 'random' module is deprecated; use the 'rand' module instead
    yaws_dynopts.erl:142: random:uniform/1: the 'random' module is deprecated; use the 'rand' module instead

The `yaws_dynopts` module replaces itself when Yaws starts, and the replacement source code (found in `yaws_dynopts:source/0`) is correct.

**Comment by capflam** [comment]
@vinoski, no, it is really a typo error. To avoid warnings on deprecated functions, in the default module, I use the fun keyword (e.g `(fun random:uniform)(N)` instead of `random:uniform(N)`). This is a trick to avoid compilation warning.
It is important to have a valid default module because the generation during Yaws start could fail.

**Comment by vinoski** [comment]
@capflam: ah, ok, now I get it. Thanks for explaining it.

**Comment by capflam** [comment]
@cmeiklejohn, I've amended your fix and I've pushed it in master branch. Thanks !

**Comment by cmeiklejohn** [comment]
Wait, what's the fix to get around the compiler warnings?

**Comment by cmeiklejohn** [comment]
I'd like to apply it to this that we maintain for our work: https://github.com/lasp-lang/rand_compat

**Comment by cmeiklejohn** [comment]
Got it; thank you! https://github.com/lasp-lang/rand_compat/commit/e3397541b68776b1f46f4c3cfc65f02724d72a8b

**Pull request closed without merging**
