### PR TITLE
Expires improvements

### PR DESCRIPTION
**Pull request by andreineculau**
2 convenience settings for `Expires`

* `always`
* `*/*` (match any content-type)

### CODE REVIEW

**Comment by capflam** [comment]
Thanks for your contribution. It's a good idea. But some parts need to be fixed before the pull request gets merged.

You've forgot to update `yaws_config.erl` to accept the type *always* in the *expires* directives. Without this addition, it will be not possible to use this feature in a configuration file (looks at the function `yaws_config:parse_expires/2`).
Then it would be good to update the documentation (*man/yaws.conf.5* and *doc/yaws.tex*) and add some tests.

Beside that, I have a remark. allowing the syntax `*/*` is a good idea. It could also be good to support `Type/*`. This requires more work but could be nice. To help you, you could see how that is handled in `yaws_config:parse_compressible_mime_types/2`.

If you have no time to work on it, I could do it, but not immediately, I'm too busy for now.

**Comment by andreineculau** [comment]
Christopher,
I updated my branch along your guidelines, but I haven't tested it one bit.

**Comment by capflam** [comment]
Nice! I'll review it very soon.

**Comment by capflam** [comment]
Hi,

I finally took the time to review and merge your patch.  I have just updated it slightly to do more stuff during the Yaws startup. Thanks for your contribution.

**Comment by andreineculau** [comment]
Great. Thank you

On Mon, Apr 13, 2015 at 9:47 PM, Christopher Faulet <
notifications@github.com> wrote:

> Hi,
>
> I finally took the time to review and merge your patch. I have just
> updated it slightly to do more stuff during the Yaws startup. Thanks for
> your contribution.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/klacke/yaws/pull/208#issuecomment-92475631>.
>



-- 
andreineculau.com <http://www.andreineculau.com>

**Pull request merged**
