### PR TITLE
Support XCode Command Line Tools

### PR DESCRIPTION
**Pull request by lucafavatellawork**
Please refer to the commit message for background of the PR.

@leoliu This PR comes from the same symptoms you reported in https://github.com/klacke/yaws/issues/389 . If you are still experiencing that, it would be great if you could test this PR.

### CODE REVIEW

**Comment by vinoski** [comment]
Thanks!

**Comment by leoliu** [comment]
Thanks.  I remember that is also my workaround while downloading the 3G xcode.

**Comment by vinoski** [comment]
Thanks for checking this, @leoliu .

**Comment by lucafavatellawork** [comment]
@vinoski @leoliu Thanks for the fast review of this PR!

**Pull request merged**
