### PR TITLE
Replaced all occurrences of "export_all" with explicit export lists.

### PR DESCRIPTION
**Pull request by ningzhang**
Compilation fails when compiling Yaws with the latest Erlang/OTP
master branch (Version 20) with the following error message:

```
compile: warnings being treated as errors
<file>.erl:<line number>: export_all flag enabled - all functions
will be exported
```

The above problem can be fixed with this patch.

### CODE REVIEW

**Comment by capflam** [comment]
This is quite boring to explicitly export functions in the testsuite modules. Because it is harder to write tests this way. Instead, we can just inhibit the warning for the whole testsuite. Could you confirm that the following patch do the trick ?

```diff
diff --git a/testsuite/Makefile.am b/testsuite/Makefile.am
index b89a3bf..7b484f5 100644
--- a/testsuite/Makefile.am
+++ b/testsuite/Makefile.am
@@ -17,7 +17,7 @@ EBIN_FILES=$(MODULES:%.erl=$(EBIN_DIR)/%.beam)
 
 LOG_DIR=@builddir@/logs
 
-ERLC_FLAGS = $(ERLC_GENERIC_FLAGS) -DSHOW_LOG
+ERLC_FLAGS = $(ERLC_GENERIC_FLAGS) -DSHOW_LOG +nowarn_export_all
 
 include @top_srcdir@/erlang_deps.mk
 
```

**Comment by ningzhang** [comment]
Sure, I'm on it.

**Comment by ningzhang** [comment]
These two files also need to be adjusted:

```
www/code/myappmod.erl
www/shoppingcart/shopcart.erl
```

Shall we use the `+nowarn_export_all` flag or an explicit export list?

**Comment by capflam** [comment]
Good catch. There is also some modules in mail and wiki applications. But for all these ones, I think, an explicit export of all public functions is the best choice. I'll try to push the fix very soon. Many thanks.

**Comment by ningzhang** [comment]
Cheers!

**Pull request closed without merging**
