### PR TITLE
New ssl option for yaws.conf: dhfile

### PR DESCRIPTION
**Pull request by phonohawk**
A fixed 1024-bit Diffie-Hellman group can no longer be considered to be safe (\*1). There should be a way to use the dhfile option (\*2) through yaws.conf.

\*1: https://weakdh.org/sysadmin.html
\*2: http://www.erlang.org/doc/man/ssl.html

### CODE REVIEW

**Comment by vinoski** [comment]
Looks good, except there are no tests included.

**Comment by phonohawk** [comment]
Yes... I know a new feature with no test case is indeed a bad thing, but I couldn't find a way to write a test which does the following:

1. Spawn a server with an unique 2048-bit Diffie-Hellman group. (Easy)
2. Connect to the server using Diffie-Hellman key exchange. (Easy)
3. Confirm that the step 2 actually used the group specified at the step 1. (Really difficult because the ssl module does not give us such a detailed information)

**Comment by vinoski** [comment]
Since this work is centered around `dhfile`, perhaps you can have a test that tries to start a server using that option but with a file that's not valid, and make sure the error occurs and Yaws handles it properly. Then have another test that just does steps 1 and 2 of your list, but this time with a valid file, as that at least makes sure Yaws starts correctly when a valid `dhfile` is supplied.

**Comment by phonohawk** [comment]
That is feasible. Thanks for your suggestion. I'll do it later.

**Comment by phonohawk** [comment]
Done.

**Comment by vinoski** [comment]
Thanks, this is now on master, but I first rebased your changes to squash your commits, and also combined the new `t12` and `t13` test directories into just `t12` with 2 virtual servers.

**Comment by phonohawk** [comment]
Thanks! I wonder why I couldn't come up with the idea how to combine those two directories :)

**Pull request closed without merging**
